startup = [
	"alias g.s = git status",
	"alias g.co = git checkout",
	"alias g.b = git branch -v --sort=committerdate",
	"alias g.c = git commit -v",
	"alias g.cv = git commit --no-verify -v",
	"alias g.log= clear; git log --graph --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white)— %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative"
]
